---
title: "CCA-1"
output:
  pdf_document: 
    latex_engin : xelatex
mainfont : NanumGothic
---

## 0. 라이브러리 및 데이터 불러오기

```{r}
library(ggplot2)
library(CCA)

df = read.csv("./bird_preprocessed.csv")
head(df)
```

## 1. CCA를 위한 X, Y 분리

-   X : length(l)
-   Y : diameter(w)

```{r}
X = df[c(1,3,5,7,9)]
head(X)

Y = df[c(2,4,6,8,10)]
head(Y)
```

## 2. X, Y 표준화 

-   X와 Y를 평균 0, 분산 1로 scaling

```{r}
Zx = scale(X)
head(Zx)
mean(Zx); diag(var(Zx))

Zy = scale(Y)
head(Zy)
mean(Zy); diag(var(Zy))
```


## 3. 표준화 변수로 CCA 진행 

```{r}
cc1 = cc(Zx,Zy)

# 정준상관계수 
cc1$cor

# 정준변수 U의 coefficient
cc1$xcoef

# 정준변수 V의 coefficient
cc1$ycoef

# U값
head(cc1$scores$xscores)

# V값
head(cc1$scores$yscores)

# corr(X,U)
colnames(cc1$scores$corr.X.xscores) <- c("U1","U2","U3","U4","U5")
cc1$scores$corr.X.xscores

# corr(Y,U)
colnames(cc1$scores$corr.Y.xscores) <- c("U1","U2","U3","U4","U5")
cc1$scores$corr.Y.xscores

# corr(X,V)
colnames(cc1$scores$corr.X.yscores) <- c("V1","V2","V3","V4","V5")
cc1$scores$corr.X.yscores

# corr(Y,V)
colnames(cc1$scores$corr.Y.yscores) <- c("V1","V2","V3","V4","V5")
cc1$scores$corr.Y.yscores
```



## 4. 정준변수 시각화

```{r, fig.width=8, fig.height=8}
U1 = cc1$scores$xscores[,1]
V1 = cc1$scores$yscores[,1]
ggplot(data.frame(U1,V1), aes(U1,V1))+geom_point()

U2 = cc1$scores$xscores[,2]
V2 = cc1$scores$yscores[,2]
ggplot(data.frame(U2,V2), aes(U2,V2))+geom_point()

plt.cc(cc1, type="v", var.label=TRUE)
plt.cc(cc1, type="i", var.label=TRUE)
ggplot(data.frame(U1,U2), aes(U1,U2))+geom_point()
```

## 5. 상관관계 시각화

```{r}
mtc = matcor(X,Y)
img.matcor(mtc, type=2)
```



## 6. 상관성 검정

```{r}
rho = cc1$cor
n = nrow(df)
p = ncol(X)
q = ncol(Y)
alpha = 0.05
c(n,p,q)

(Lambda = prod(1-rho^2))
term = -(n-(p+q+3)/2)
chi_stat = term*log(Lambda)
chi = qchisq(1 - alpha, p*q)
p_value = 1 - pchisq(chi_stat, p*q)
c(chi_stat, chi, p_value) 

if (chi_stat < chi){
  print("귀무가설 채택, X와 Y 사이에 상관성이 없다.")
} else{
  print("귀무가설 기각, X와 Y 사이에 상관성이 있다.")
}
```



## 7. 다중상관계수제곱

```{r}
# R{Y1|X}
rho = cc1$cor
sum((cc1$scores$corr.Y.xscores[1,])^2 * rho^2)

# X 집합에서 생성된 정준변수와 각 Y변수 간의 상관계수를 제곱 : 각 Y변수의 분산 중 X 정준변수에 의해 설명되는 비율,
# 정준상관계수 제곱을 곱함 : 첫번째 정준변수쌍이 Y의 전체 분산을 얼마나 잘 설명하는지
# 첫 번째 정준변수 쌍이 Y 집합의 변수들의 전체 분산 중 얼마나 설명하는지를 종합적으로 나타내는 값.

sum((cc1$scores$corr.Y.xscores[2,])^2 * rho^2)

sum((cc1$scores$corr.Y.xscores[3,])^2 * rho^2)

sum((cc1$scores$corr.Y.xscores[4,])^2 * rho^2)

sum((cc1$scores$corr.Y.xscores[5,])^2 * rho^2)
```

